services:
  prism:
    container_name: "ddev-${DDEV_SITENAME}-prism"
    image: stoplight/prism:4
    command: 'mock -h 0.0.0.0 -p 4010 /tmp/openapi.yaml'
    volumes:
      - ../openapi.yaml:/tmp/openapi.yaml:ro
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
    restart: "no"
    ports:
      - "4010"

